In [1]:
import os
RAND_SEED = 12345
import numpy as np
np.random.seed(RAND_SEED)
import random
random.seed(RAND_SEED)
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from statsmodels.tools.tools import add_constant
import statsmodels
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
from google.colab import files
uploaded = files.upload()

Saving data.zip to data.zip


In [3]:
!unzip data

Archive:  data.zip
  inflating: data/Critical_Oil_Rate.csv  
  inflating: data/Threshold radius.csv  
  inflating: data/Well_Choke_GL.csv  
  inflating: data/Well_Monthly_Production.csv  
  inflating: data/Well_Rates.csv     


In [4]:
# Define directories and file names
cwd = os.getcwd()
DataFolder = os.path.join(cwd, 'data')
InputDataFile = os.path.join(DataFolder, 'Threshold radius.csv')

In [5]:
df = pd.read_csv(InputDataFile)
df.head()

Oil-zone thickness  Mobility  ...  Anisotropy ratio  Threshold_radius
0                  25         1  ...               0.1              4000
1                  25         1  ...               0.1              7000
2                  25        10  ...               0.1              1000
3                  25        10  ...               0.1              1000
4                 150         1  ...               0.1             16000

[5 rows x 7 columns]

In [6]:
# Build input matrix and target vector
x = df.drop(['Threshold_radius'], axis=1)
Y = df.Threshold_radius.values

In [7]:
# Transform the x data for proper fitting (for single variable type it returns,[1,x,x**2])
poly = PolynomialFeatures(2)
x = poly.fit_transform(x)
print(x)
len(x)

[[1.0e+00 2.5e+01 1.0e+00 ... 2.5e-01 5.0e-02 1.0e-02]
 [1.0e+00 2.5e+01 1.0e+00 ... 2.5e-01 5.0e-02 1.0e-02]
 [1.0e+00 2.5e+01 1.0e+01 ... 2.5e-01 5.0e-02 1.0e-02]
 ...
 [1.0e+00 7.5e+01 3.0e+00 ... 2.5e-01 5.0e-02 1.0e-02]
 [1.0e+00 7.5e+01 3.0e+00 ... 2.5e-01 5.0e-02 1.0e-02]
 [1.0e+00 7.5e+01 3.0e+00 ... 2.5e-01 5.0e-02 1.0e-02]]


54

In [8]:
# Compute input feature X adding a constant
X = sm.add_constant(x)

In [9]:
# Build OLS Regression model and fit input data
model = sm.OLS(Y, X).fit()

In [10]:
# Make predictions
predictions = model.predict(X) 
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.948
Model:                            OLS   Adj. R-squared:                  0.894
Method:                 Least Squares   F-statistic:                     17.52
Date:                Fri, 24 Dec 2021   Prob (F-statistic):           8.28e-11
Time:                        05:40:57   Log-Likelihood:                -464.79
No. Observations:                  54   AIC:                             985.6
Df Residuals:                      26   BIC:                             1041.
Df Model:                          27                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.366e+04   4170.610      3.275      0.003    5086.530    2.22e+04
x1            71.6339     38.699      1.851      0.076      -7.912     151.180
x2         -3821.9108    615.202     -6.212      0.000   -5086.476   -2557.345
x3           -68.0399     17.645     -3.856      0.001    -104.310     -31.770
x4            25.8608     20.375      1.269      0.216     -16.020      67.742
x5          4019.7815   8151.248      0.493      0.626   -1.27e+04    2.08e+04
x6         -3.882e+04   9789.175     -3.966      0.001   -5.89e+04   -1.87e+04
x7             0.2090      0.171      1.221      0.233      -0.143       0.561
x8            -9.7649      2.189     -4.462      0.000     -14.264      -5.266
x9            -0.1018      0.040     -2.566      0.016      -0.183      -0.020
x10            0.0657      0.032      2.061      0.049       0.000       0.131
x11           -1.9916     34.902     -0.057      0.955     -73.734      69.751
x12            0.6299     18.199      0.035      0.973     -36.779      38.039
x13          312.9730     46.676      6.705      0.000     217.030     408.916
x14            1.5478      0.512      3.022      0.006       0.495       2.601
x15           -1.1082      0.541     -2.049      0.051      -2.220       0.004
x16           -9.2260    340.944     -0.027      0.979    -710.046     691.594
x17          175.2544    242.674      0.722      0.477    -323.569     674.078
x18            0.1092      0.030      3.661      0.001       0.048       0.171
x19           -0.0109      0.010     -1.129      0.269      -0.031       0.009
x20           -0.0196      8.158     -0.002      0.998     -16.789      16.750
x21            3.1126      3.438      0.905      0.374      -3.955      10.180
x22           -0.0332      0.034     -0.983      0.335      -0.103       0.036
x23           -0.0170      8.760     -0.002      0.998     -18.024      17.990
x24            3.1498      4.614      0.683      0.501      -6.335      12.634
x25        -3839.7980   6896.662     -0.557      0.582    -1.8e+04    1.03e+04
x26          330.0356   3687.507      0.090      0.929   -7249.744    7909.815
x27         3.353e+04   8734.586      3.839      0.001    1.56e+04    5.15e+04
==============================================================================
Omnibus:                        0.093   Durbin-Watson:                   1.954
Prob(Omnibus):                  0.954   Jarque-Bera (JB):                0.264
Skew:                           0.072   Prob(JB):                        0.876
Kurtosis:                       2.689   Cond. No.                     7.23e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.23e+06. This might i

In [11]:
# Prepare data for two-step backward elimination process
ho = df.iloc[:,0].values
M  = df.iloc[:,1].values
hw = df.iloc[:,2].values
Kh = df.iloc[:,3].values
p  = df.iloc[:,4].values
I  = df.iloc[:,5].values

In [12]:
# Preparing the data according to a degree 4 polynomial scheme :
S_poly        = np.zeros((54, 28))
S_poly[:,0]   = np.ones(1)
S_poly[:, 1]  = ho
S_poly[:, 2]  = M
S_poly[:, 3]  = hw
S_poly[:, 4]  = Kh
S_poly[:, 5]  = p
S_poly[:, 6]  = I
S_poly[:, 7]  = ho*ho
S_poly[:, 8]  = ho*M
S_poly[:, 9]  = ho*hw
S_poly[:, 10] = ho*Kh
S_poly[:, 11] = ho*p
S_poly[:, 12] = ho*I
S_poly[:, 13] = M*M
S_poly[:, 14] = M*hw
S_poly[:, 15] = M*Kh
S_poly[:, 16] = M*p
S_poly[:, 17] = M*I
S_poly[:, 18] = hw*hw
S_poly[:, 19] = hw*Kh
S_poly[:, 20] = hw*p
S_poly[:, 21] = hw*I
S_poly[:, 22] = Kh*Kh
S_poly[:, 23] = Kh*p
S_poly[:, 24] = Kh*I
S_poly[:, 25] = p*p
S_poly[:, 26] = p*I
S_poly[:, 27] = I*I

In [13]:
# Removing insgnificant factors with p-value>0.5
x_opt = S_poly[:, [0, 1, 2, 3, 4, 6, 7, 8, 9,10,13,14,15,17,18,19,21,22,27]]

In [14]:
# Build OLS Regression model and fit input data
model = sm.OLS(endog = Y, exog = x_opt).fit() 
model.summary() 

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.946
Model:                            OLS   Adj. R-squared:                  0.919
Method:                 Least Squares   F-statistic:                     34.22
Date:                Fri, 24 Dec 2021   Prob (F-statistic):           5.21e-17
Time:                        05:41:16   Log-Likelihood:                -465.64
No. Observations:                  54   AIC:                             969.3
Df Residuals:                      35   BIC:                             1007.
Df Model:                          18                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.467e+04   2569.611      5.709      0.000    9453.419    1.99e+04
x1            70.7834     28.148      2.515      0.017      13.641     127.926
x2         -3756.2102    513.537     -7.314      0.000   -4798.746   -2713.675
x3           -71.3467     14.537     -4.908      0.000    -100.858     -41.835
x4            23.7781     17.101      1.390      0.173     -10.938      58.494
x5         -3.848e+04   8051.946     -4.779      0.000   -5.48e+04   -2.21e+04
x6             0.2082      0.144      1.443      0.158      -0.085       0.501
x7            -9.7110      1.908     -5.090      0.000     -13.584      -5.837
x8            -0.1010      0.034     -2.985      0.005      -0.170      -0.032
x9             0.0646      0.027      2.358      0.024       0.009       0.120
x10          306.5470     40.129      7.639      0.000     225.080     388.014
x11            1.5347      0.448      3.427      0.002       0.625       2.444
x12           -1.0922      0.467     -2.338      0.025      -2.041      -0.144
x13          155.4989    211.295      0.736      0.467    -273.453     584.451
x14            0.1147      0.025      4.535      0.000       0.063       0.166
x15           -0.0091      0.008     -1.107      0.276      -0.026       0.008
x16            3.4284      2.979      1.151      0.258      -2.619       9.476
x17           -0.0285      0.029     -0.981      0.333      -0.087       0.030
x18          3.39e+04   7518.710      4.508      0.000    1.86e+04    4.92e+04
==============================================================================
Omnibus:                        0.138   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.933   Jarque-Bera (JB):                0.305
Skew:                           0.094   Prob(JB):                        0.859
Kurtosis:                       2.684   Cond. No.                     6.79e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.79e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [15]:
# Removing insgnificant factors with p-value>0.15
x_opt = S_poly[:, [0, 1, 2, 3,6,8,9,10,13,14,15,18,27]]

In [16]:
# Build OLS Regression model and fit input data
model = sm.OLS(endog = Y, exog = x_opt).fit() 
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.931
Model:                            OLS   Adj. R-squared:                  0.911
Method:                 Least Squares   F-statistic:                     46.43
Date:                Fri, 24 Dec 2021   Prob (F-statistic):           5.79e-20
Time:                        05:41:20   Log-Likelihood:                -472.20
No. Observations:                  54   AIC:                             970.4
Df Residuals:                      41   BIC:                             996.3
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.492e+04   1581.250      9.436      0.000    1.17e+04    1.81e+04
x1            99.6519     11.805      8.441      0.000      75.811     123.493
x2         -3563.7670    494.277     -7.210      0.000   -4561.979   -2565.555
x3           -68.5138     14.225     -4.816      0.000     -97.243     -39.785
x4         -3.459e+04   7998.464     -4.324      0.000   -5.07e+04   -1.84e+04
x5           -10.1272      1.980     -5.115      0.000     -14.126      -6.128
x6            -0.0874      0.035     -2.504      0.016      -0.158      -0.017
x7             0.1036      0.020      5.136      0.000       0.063       0.144
x8           288.0022     38.347      7.510      0.000     210.559     365.445
x9             1.4974      0.451      3.320      0.002       0.586       2.408
x10           -0.5482      0.397     -1.382      0.174      -1.349       0.253
x11            0.1072      0.025      4.247      0.000       0.056       0.158
x12         3.129e+04   7548.070      4.145      0.000     1.6e+04    4.65e+04
==============================================================================
Omnibus:                        0.692   Durbin-Watson:                   1.956
Prob(Omnibus):                  0.707   Jarque-Bera (JB):                0.702
Skew:                           0.253   Prob(JB):                        0.704
Kurtosis:                       2.762   Cond. No.                     5.55e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.55e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""